# Generated by Django 4.1 on 2022-10-21 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caculate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Monthly_Slary', models.PositiveIntegerField()),
                ('Bonifications', models.PositiveIntegerField()),
                ('Extra_Hours', models.PositiveIntegerField()),
            ],
        ),
    ]
