# Generated by Django 4.1 on 2022-10-21 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SalaryCalculator', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Caculate',
        ),
    ]
